### ISSUE TITLE
Install/Run Instructions and SQLAlchemy Issue

### ISSUE THREAD

**Issue by kecalli** [OpenKMIP/PyKMIP#193] opened 2016-09-22 11:38 UTC
I have installed the latest version of pykmip-server (0.5.0) but have some questions.

I noticed that the instructions on the Wiki mention to run the "run_server.py" script but it appears as though the newer versions of pykmip support installation of Pykmip-server using the easy-install/pip method (python server.py build/install).  Is the easy-install/pip the preferred method of installing now?

When I start the server (0.5.0) using the pykmip-server script in /bin, I am receiving the following message:

/usr/lib/python3.4/site-packages/SQLAlchemy-1.1.0b3-py3.4-linux-x86_64.egg/sqlalchemy/orm/mapper.py:1034: SAWarning: Reassigning polymorphic association for identity 'Certificate' from <Mapper at 0x7f2fa55a99b0; Certificate> to <Mapper at 0x7f2fa55a9eb8; X509Certificate>: Check for duplicate use of 'Certificate' as value for polymorphic_identity

I have generated certs and they are signed by a CA.  I even tried using the demo certs that were included.  It appears as though the server still runs with after this message is displayed but wasn't sure if it is a warning or is causing other issues.  I confirmed that I am binding to port 5696 on a public interface and enabled logging.  I'm not currently able to connect from my client.

The message I receive in the log when a client attempts to connect is:

2016-09-21 16:08:35,948 - kmip.server.session.00000001 - WARNING - An unexpected error occurred while processing request.
2016-09-21 16:08:35,948 - kmip.server.session.00000001 - ERROR - 'NoneType' object has no attribute 'credential'
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.5.0-py3.4.egg/kmip/services/server/session.py", line 106, in _handle_message_loop
    request
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.5.0-py3.4.egg/kmip/services/server/engine.py", line 142, in decorator
    return function(self, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/PyKMIP-0.5.0-py3.4.egg/kmip/services/server/engine.py", line 252, in process_request
    auth_credentials = header.authentication.credential
AttributeError: 'NoneType' object has no attribute 'credential'

Last question.  I tried going back to a previous version of PyKmip (such as 0.4.1) since this is prior to using sqlalchemy.  When I install this, there is no pykmip-server in /bin and I see no run_server.py.  I tried running the kmip/services/server/server.py script but it runs and then exits right away.  What is the preferred way to run in version 0.4.1?

Sorry for all of the questions and thanks for your hard work.  I would greatly appreciate any help you can provide.

**Comment by joel-coffman** [comment] 2016-09-23 12:58
I'll answer the easiest question:

> What is the preferred way to run in version 0.4.1?

The PyKMIP server was added in version 0.5.0 (see [CHANGES](https://github.com/OpenKMIP/PyKMIP/blob/master/CHANGES.txt)). Anything that existed prior to that time had very limited functionality -- essentially some sanity checks on the requests and responses for testing the client.

@PeterHamilton is the best person to address the rest of your questions.

**Comment by PeterHamilton** [comment] 2016-09-26 16:29
Hi @kecalli, thanks for filing this issue. I've been out on vacation so I apologize for not getting to this sooner.

@joel-coffman is correct regarding version 0.4.1. Version 0.5.0 introduced a more mature server implementation that actually supports basic key management functionality; the 0.4.1 version (and prior) was really only good for sanity checks and networking tests.

Let's sanity check things first. Did you install PyKMIP 0.5.0 via pip or did you clone master from the GitHub repo and install that?

**Comment by kecalli** [comment] 2016-09-26 16:58
Hi Peter,

No problem.  Hope you enjoyed your vacation.

I have tried either the stable 0.5.0 release or cloning the master from
Github.  In all cases, I installed using the "setup.py build/install"
process which I believe uses pip directly? It appears that I experience the
same results either way.

Thanks,

Keith

**Comment by vvadimka** [comment] 2016-09-28 15:34
Hi, Peter , just saw this topic and wanted to add that I am also getting the same error 
I installed OpenKMIP release 0.5 and have a python 2.7 (latest version)
All certificates are installed and configured in the server and client configuration files



2016-09-28 11:16:57,719 - kmip.server.session.00000001 - ERROR - 'NoneType' object has no attribute 'credential'
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\pykmip-0.5.0-py2.7.egg\kmip\services\server\session.py", line 106, in _handle_message_loop
    request
  File "c:\Python27\lib\site-packages\pykmip-0.5.0-py2.7.egg\kmip\services\server\engine.py", line 142, in decorator
    return function(self, *args, **kwargs)
  File "c:\Python27\lib\site-packages\pykmip-0.5.0-py2.7.egg\kmip\services\server\engine.py", line 252, in process_request
    auth_credentials = header.authentication.credential
AttributeError: 'NoneType' object has no attribute 'credential'
2016-09-28 11:16:57,723 - kmip.server.session.00000001 - INFO - Stopping session: 00000001


I will very appreciate if you can maybe explain what does this error mean ?
Thanks,
Vadim

**Comment by PeterHamilton** [comment] 2016-09-28 20:48
Unfortunately something's come up that has taken over my time. I'm planning on looking into this tomorrow/Friday. I haven't forgotten!

**Comment by PeterHamilton** [comment] 2016-09-30 13:22
Ok, I'm running through some tests on this now. I suspect this is a bug on the server side, where it expects to see a credential coming from the client with the KMIP `Create` request. If I'm correct, a fix for this should be pretty easy. I'll post back once I've confirmed this.

**Comment by PeterHamilton** [comment] 2016-09-30 14:16
I think I've identified the problem, but I'll need to confirm something with you both. 

First: are you both using the PyKMIP client, or one of the client demo scripts in `kmip/demos`?
Second: if so, do you have username/password fields defined in your `pykmip.conf` file?

If the answer to #2 is no, the PyKMIP client will not send a credential with the server request, causing the error you're both seeing. The username/password fields can be empty in the `pykmip.conf` file, like so:

    [client]
    hostname=127.0.0.1
    port=5696
    ...
    username=
    password=

It's a quirk of how the client currently works that's apparently not covered in our tests. Add those two lines to your `pykmip.conf` and things should work.

Regardless, the server should not generate an error on missing credentials (especially since they're not required). I'll post a server-side fix for this shortly.

**Comment by vvadimka** [comment] 2016-09-30 15:30
Hi, Peter 

Many thanks for your help. You are right , I used kmip/demos  samples and user/passwords fields were missing
After I added them , the samples start working .
Again , thanks for your quick reply.

Thanks,
Vadim

**Comment by PeterHamilton** [comment] 2016-09-30 15:54
Awesome, glad that was the right fix. Once I patch the client and server, this shouldn't be a problem again.

**Comment by PeterHamilton** [comment] 2016-10-03 15:18
@kecalli - Going back to your first question regarding SQLAlchemy, that is a warning I've seen for a while now that I believe is related to a bug in how the `Certificate` object is mapped to the database. So far it hasn't produced any breaking behavior, so it hasn't been high on my fix list. I'll file a separate issue for it so that it can be tracked independently of this server bug.

**Closed** 2016-10-03 17:50 UTC
Labels: bug, client, help wanted, server
