### ISSUE TITLE
runserver.py prints warning at startup

### ISSUE THREAD

**Issue by toothwalker** [OpenKMIP/PyKMIP#204] opened 2016-11-16 18:50 UTC
> /home/toothwalker/.local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1034: SAWarning: Reassigning polymorphic association for identity 'Certificate' from <Mapper at 0x7fb3e7980410; Certificate> to <Mapper at 0x7fb3e7980910; X509Certificate>: Check for duplicate use of 'Certificate' as value for polymorphic_identity.
  self, self.polymorphic_identity)

**Comment by PeterHamilton** [comment] 2016-11-16 20:32
Yep, this is a `sqlalchemy` warning regarding how the `Certificate` object is defined. The warning itself has been around for a while. To be honest, since it doesn't seem to break anything I've never taken the time to debug it. If you have any insight, I'm happy to take a look.

**Comment by PeterHamilton** [comment] 2017-01-04 17:21
I believe this is caused by the reuse of the string `Certificate` for both the `Certificate` and `X509Certificate` objects. PR https://github.com/OpenKMIP/PyKMIP/pull/240 should fix this.

**Comment by PeterHamilton** [comment] 2017-01-06 04:00
PR #240 has merged so this should be fixed. Let me know if you see it pop up again.

**Closed by PeterHamilton** 2017-01-06 04:00 UTC
Labels: bug

**Comment by santosh253** [comment] 2017-04-12 16:16
Getting same error with latest PyPI package




root@ubuntu:~# /root/PyKMIP/bin/run_server.py
/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py:1034: SAWarning: Reassigning polymorphic association for identity 'Certificate' from <Mapper at 0x7f52ed966cd0; Certificate> to <Mapper at 0x7f52ed910210; X509Certificate>: Check for duplicate use of 'Certificate' as value for polymorphic_identity.
  self, self.polymorphic_identity)

**Comment by PeterHamilton** [comment] 2017-04-12 16:22
Yep, the bug fix is only on the master branch of the project right now so you'd only get it if you pulled from GitHub directly. It will be included with 0.7.0 once that gets released. I'd like to release a 0.6.1 for it but given it's not a breaking issue I'm not that worried about it.
