### ISSUE TITLE
Fails with the following error

### ISSUE THREAD

**Issue by schlutech** [OpenKMIP/PyKMIP#459] opened 2018-11-12 19:29 UTC
Could use some help from the experts. I keep getting the following repeating.... can't get it any further. Anyone offer assistance?

2018-11-12 14:24:18,541 - kmip.server.session.00000011 - DEBUG - Session cipher selected: ('AES256-SHA', 'TLSv1/SSLv3', 256)
2018-11-12 14:24:18,542 - kmip.server.session.00000011 - WARNING - Failure parsing request message.
2018-11-12 14:24:18,542 - kmip.server.session.00000011 - ERROR - Tried to read Base.type: expected 7, received 2
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/PyKMIP-0.9.dev0-py3.5.egg/kmip/services/server/session.py", line 157, in _handle_message_loop
    request.read(request_data)
  File "/usr/local/lib/python3.5/dist-packages/PyKMIP-0.9.dev0-py3.5.egg/kmip/core/messages/messages.py", line 351, in read
    batch_item.read(istream)
  File "/usr/local/lib/python3.5/dist-packages/PyKMIP-0.9.dev0-py3.5.egg/kmip/core/messages/messages.py", line 201, in read
    self.request_payload.read(tstream)
  File "/usr/local/lib/python3.5/dist-packages/PyKMIP-0.9.dev0-py3.5.egg/kmip/core/messages/payloads/locate.py", line 73, in read
    attr.read(tstream)
  File "/usr/local/lib/python3.5/dist-packages/PyKMIP-0.9.dev0-py3.5.egg/kmip/core/objects.py", line 119, in read
    self.attribute_value.read(tstream)
  File "/usr/local/lib/python3.5/dist-packages/PyKMIP-0.9.dev0-py3.5.egg/kmip/core/primitives.py", line 835, in read
    super(TextString, self).read(istream)
  File "/usr/local/lib/python3.5/dist-packages/PyKMIP-0.9.dev0-py3.5.egg/kmip/core/primitives.py", line 106, in read
    self.read_type(istream)
  File "/usr/local/lib/python3.5/dist-packages/PyKMIP-0.9.dev0-py3.5.egg/kmip/core/primitives.py", line 84, in read_type
    typ
kmip.core.exceptions.ReadValueError: Tried to read Base.type: expected 7, received 2

**Comment by PeterHamilton** [comment] 2018-11-12 19:34
Hi @schlutech. This looks like a message decoding error from the PyKMIP server. What client are you using to talk to the server? What operation are you trying to perform?

**Comment by schlutech** [comment] 2018-11-12 20:07
I am using my storage array. Trying to get through the initial server/client setup so as to start creating keys for self-encrypting disks.

**Comment by PeterHamilton** [comment] 2018-11-12 20:18
Are you using the PyKMIP client? It looks like the request you're sending to the server has a malformed KMIP Attribute object, specifically a KMIP TextString value. If you're using the PyKMIP client, I can probably walk you through fixing your code to get this working.

**Comment by PeterHamilton** [comment] 2018-11-12 20:39
It's going to be hard to fix this if the array client is sending malformed requests. I'm not familiar with which KMIP client Dell uses. The documentation for the array **may** have configuration options that control the logging level for the client; if those exist, you can experiment with those.

Alternatively, I can tell you how to modify the PyKMIP server source code to add a logging line that will log the request the server receives. Using that, we could determine what part of the request message is malformed. It wouldn't exactly allow us to fix things, but you could use that information to file a bug report with Dell.

If the array client really is sending malformed requests, I would expect this failure to show up with any KMIP server. It would be useful to test against something else, but I don't know of any other alternatives that don't have a price tag.

**Comment by PeterHamilton** [comment] 2018-11-12 20:40
It's also possible that the array client may produce logs. Do you have access to those? If they exist, they would be helpful.

**Comment by schlutech** [comment] 2018-11-12 21:01
I went the way of trying to diagnose on the client side. I am sure its possible, but not available to their customers. If I could find a smoking gun I feel it would really help to get a patch from the vendor.

**Comment by PeterHamilton** [comment] 2018-11-12 21:03
Agreed. Let me know if you do want to pursue a PyKMIP server-side modification. That unfortunately may be the only way to really nail this down.

**Comment by schlutech** [comment] 2018-11-12 21:03
I tested against multiple KMIP commercial vendors who also failed. Gemalto Safenet is successful.

**Comment by schlutech** [comment] 2018-11-12 21:04
Yes please.

**Comment by PeterHamilton** [comment] 2018-11-12 21:37
I guess you found the KMIP server Dell tested against. I've encountered issues with Safenet KMIP compliance causing problems before (see #78) but in this case it works in your favor.

You'll need to locate the PyKMIP source code on your system. You're looking specifically for the following file:

`<PyKMIP root>/kmip/services/server/session.py`.

It should look like this file: [session.py](https://github.com/OpenKMIP/PyKMIP/blob/master/kmip/services/server/session.py). If it doesn't, let me know what version of PyKMIP you're using. That will change the instructions below. Use the following command to get the PyKMIP version:

`python -c "from __future__ import print_function; import kmip; print(kmip.__version__)"`

If the above file looks like the linked one, we can go ahead and make the modification.

**This modification will dump sensitive information in the server log file. Remove the modification and the log file once you are finished.**

Stop the server if it's running and then create a backup copy of `session.py` so you have a good copy to refer to if needed. Go to lines 114-116. You should see a `request_data` variable defined on line 114. `request_data` contains the request in byte format once the server receives it; we want to log this so we can see what the server is receiving from the client.

Add the following lines starting on line 116 (which should be blank):

```
import binascii
self._logger.debug("Request bytes: {0}".format(binascii.hexlify(request_data)))
```

The server should now dump each request to the server log file. Go to your server configuration file and make sure the `logging_level` configuration option is set to `DEBUG` (see the [docs](https://pykmip.readthedocs.io/en/latest/server.html#configuration) for more info).

Start the server and check the server log to make sure its running fine. If it is, go ahead and have the Dell array make another KMIP request. You should see the failure in the log, along with the bytes for the request. For diagnosing where the array client is going wrong, I'll need to pick apart this request encoding. Email it to me if you are comfortable doing so.

**These request bytes may contain sensitive information for your setup (e.g., usernames, passwords). Change any passwords or sensitive information if you do send these bytes to anyone, including me.**

**Comment by schlutech** [comment] 2018-11-12 22:08
The version is: 0.9.dev0. I am running tests now.

**Comment by schlutech** [comment] 2018-11-12 22:15
Let me guess... I messed up my indentations? ;)

2018-11-12 17:14:05,239 - kmip.server.session.00000003 - ERROR - a bytes-like object is required, not 'BytearrayStream'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/PyKMIP-0.9.dev0-py3.5.egg/kmip/services/server/session.py", line 102, in run
    self._handle_message_loop()
  File "/usr/local/lib/python3.5/dist-packages/PyKMIP-0.9.dev0-py3.5.egg/kmip/services/server/session.py", line 117, in _handle_message_loop
    self._logger.debug("Request bytes: {0}".format(binascii.hexlify(request_data)))
TypeError: a bytes-like object is required, not 'BytearrayStream'

**Comment by PeterHamilton** [comment] 2018-11-13 13:35
No problem, I'm happy to help.

I goofed on the debug line. It should be this instead:

```
import binascii
self._logger.debug("Request bytes: {0}".format(binascii.hexlify(request_data.buffer)))
```

**Comment by schlutech** [comment] 2018-11-13 15:03
Excellent! Here is the output.

[kmip.log](https://github.com/OpenKMIP/PyKMIP/files/2576791/kmip.log)

**Comment by PeterHamilton** [comment] 2018-11-13 16:10
Awesome, I'm glad that worked. I'll provide a breakdown of what the KMIP request contains, followed by an explanation of what's causing the error.

The array client is using the KMIP 1.0 protocol. The request message it sends contains 4 operation requests (i.e., function calls) for the PyKMIP server.

1. It first passes a `Query` operation, asking the server for information on the KMIP operations and object types it supports. It also asks the server for identifying information and for a list of the application namespaces it supports.
2. It then passes a `Locate` operation in an attempt to find a specific object (i.e., encryption key) stored by the server. It provides two attributes to filter these results, a `x-ResourceID` attribute (value: `san01-pod1-las1 351538/351539`) and a `x-SystemID` attribute (value: `351538`).
3. It then passes a `Get` operation to retrieve the first object found by the prior `Locate` operation. It specifically asks for the object to be returned in an `Opaque` format.
4. It finally passes a `GetAttributes` operation to retrieve a specific set of attributes associated with the object it just retrieved. These attributes include:
  * the `UniqueIdentifier` of the object
  * the `ObjectType` of the object
  * the `InitialDate` of the object (e.g., when the object was first created)
  * the `State` of the object (e.g., is it usable? is it archived?)
  * the `Digest` of the object (e.g., a hash of the object)
  * the `x-ResourceID` of the object
  * the `x-SystemID` of the object

The error is caused by (2) above. The array client is sending two custom attributes with that `Locate` operation call, `x-ResourceID` and `x-SystemID`; in KMIP, custom attributes begin with a `x-`. KMIP servers must be built and configured to understand what each custom attribute means. This includes how to encode and decode these values into the KMIP binary format. The PyKMIP server doesn't know what these attributes are, so it makes a best guess effort to decode them as text strings. This works for the first attribute (`x-ResourceID`) but fails for the second (`x-SystemID`) because the second is encoded as an integer. This is the error you're seeing in the server log.

Ultimately, the array client is behaving normally. It *is not* sending malformed messages. However, it is sending messages that require custom server knowledge to decode properly. If you run the array client against a KMIP server that doesn't recognize these attributes, or that cannot handle arbitrary custom attributes, it won't work. As a result, I would guess that Safenet servers (1) come prebaked with support for `x-ResourceID` and `x-SystemID` attributes, and/or (2) can handle generic custom attributes in a very robust manner.

So what's the takeaway here? In the short term, you're probably stuck using that Safenet server for your key management. You can contact Dell and/or the other server vendors you tested against and let them know that you've encountered this issue and that it causes compatibility problems across devices. I personally shy away from using custom attributes for this exact reason; it limits your options when deploying devices and services. These vendors may be willing to update their servers/clients to get around this issue but I suspect they won't.

As for PyKMIP, there's not much I can do in the short term. I would love for PyKMIP's custom attribute handling to seamlessly handle any type of attribute it gets but adding that support would likely take several weeks of effort; the attribute handling system in PyKMIP is...complex. For now, I can file an feature request issue detailing this item and it to my backlog. I don't have much time to work on new PyKMIP features right now but I can let you know if I do get around to it.

**Comment by schlutech** [comment] 2018-11-13 17:17
Excellent, thank you so much. I will file my bug reports with the vendors. I know your time is precious. Perhaps you could suggest a bounty for the feature? I could imagine that this type of issue might occur in multiple circumstances. It would be nice to see a log entry and perhaps a configuration where you can match attribute to type? Just some thoughts.

**Comment by PeterHamilton** [comment] 2018-11-13 17:45
No problem @schlutech, I'm glad I was able to help. I've added #460 to track this feature request going forward, including your feature ideas. Feel free to comment there if you have additional ideas or feedback. Good luck working with the other vendors!

I'm going to close this issue unless you have anything else you'd like to work through.

**Comment by schlutech** [comment] 2018-11-13 18:08
Thank you again.

**Comment by PeterHamilton** [comment] 2018-11-13 18:10
You're welcome!

**Closed by PeterHamilton** 2018-11-13 18:10 UTC
Labels: feature request, help wanted, server
