### ISSUE TITLE
Failures in client integration tests

### ISSUE THREAD

**Issue by toothwalker** [OpenKMIP/PyKMIP#205] opened 2016-11-16 19:08 UTC
Steps I took

1. Created certificates
1. Created /etc/pykmip/server.conf
1. Modified kmip/pykmip.conf to use new certs
1. ./bin/run_server.py
1. tox -e integration -- --config client

> 4 tests deselected
7 failed, 12 passed, 4 deselected in 2.59 seconds
ERROR: InvocationError: '/home/toothwalker/PyKMIP/.tox/integration/bin/py.test --strict kmip/tests/integration -m not ignore --config client'

Files of interest: (note: added .txt for github to accept them)
[pykmip.conf.txt](https://github.com/OpenKMIP/PyKMIP/files/595661/pykmip.conf.txt)
[server.conf.txt](https://github.com/OpenKMIP/PyKMIP/files/595667/server.conf.txt)
[server.log.txt](https://github.com/OpenKMIP/PyKMIP/files/595648/server.log.txt)
[test_output.txt](https://github.com/OpenKMIP/PyKMIP/files/595655/test_output.txt)

**Comment by PeterHamilton** [comment] 2016-11-16 20:38
Thanks for reporting this (and for being so thorough). The integration test suite was originally designed to work against actual KMIP devices, various third-party servers that support the KMIP spec. The PyKMIP server has always had some issues running correctly with it and some of the recent feature additions definitely break some of the test suite assumptions. Some things need to be improved in the server as a result and the test suite itself definitely needs to be updated.

All that to say, I will try to take a look at this soonish, though I cannot guarantee that'll be before the next release (in a few weeks most likely).

**Comment by PeterHamilton** [comment] 2017-01-05 23:57
Ok, I've done some work running the integration tests against the server and I believe `GetAttributeList` was the only operation missing required for the tests. PR https://github.com/OpenKMIP/PyKMIP/pull/242 should add that in, so I believe the integration should be good to go with regards to the server. I'll continuing testing to make sure both are compatible.

**Comment by PeterHamilton** [comment] 2017-01-06 03:59
Looking again at the server log you posted, there are a bunch of SQLAlchemy errors when looking up secrets. I haven't been able to reproduce those errors in my test runs (the only error I had was operation failure for `GetAttributeList` since it wasn't supported). In theory those errors shouldn't be occurring; the test suite usually creates the secrets it then tries to retrieve. This looks like it's just failing to create the secrets.

I'll keep an eye out for these errors you were getting as I keep working on the test suite. If you still see these whenever you run the integration tests again let me know.

**Comment by PeterHamilton** [comment] 2017-01-10 16:18
I'm going to close this for now given the integration tests appear to be stable. If you see additional errors feel free to continue using this thread and I'll reopen it.

**Closed by PeterHamilton** 2017-01-10 16:18 UTC
Labels: bug, server, testing, todo
